- name: Setup Nagios Monitoring Client
  hosts: clients
  become: true
  roles:
    - install_nagios_dependencies
    - install_nagios_client
  tasks:
    - name: Extract NRPE command names for Nagios Client
      set_fact:
        nrpe_commands: "{{ nrpe_commands }}"

- name: Ensure nrpe_commands is available from clients
  hosts: servers
  become: true
  tasks:
    - name: Retrieve nrpe_commands from a client host
      set_fact:
        nrpe_commands: "{{ hostvars[item].nrpe_commands }}"
      # groups['clients'][0] pobiera pierwszy host z grupy clients (możesz dostosować do swoich potrzeb)
      loop: "{{ groups['clients'] }}"
    
    - name: Add clients to Nagios Server
      include_role:
        name: add_nagios_clients_to_server


    # - name: Generate Nagios client config
    #   debug:
    #     msg: "NRPE commands: {{ nrpe_commands }}"

    
# - name: Display hostvars for all hosts
#   hosts: clients
#   tasks:
#     - name: Show hostvars structure
#       debug:
#         var: hostvars


# - name: Add client to Nagios Server
#   hosts: servers
#   roles:
#     - add_nagios_clients_to_server
