- name: Setup Nagios Monitoring Server
  hosts: AnsibleTarget2
  become: true
  roles:
    - install_nagios_client

- name: Setup Nagios Monitoring Server
  hosts: AnsibleTarget2
  become: true
  roles:
    - install_nagios_client