- name: Install NRPE package
  dnf:
    name: nrpe
    state: present

- name: Install NRPE plugin for Nagios
  dnf:
    name: nagios-plugins-nrpe
    state: present

- name: Check if check_nrpe exists at least in one location
  stat:
    path: "{{ item }}"
  register: check_nrpe_check
  with_items:
    - /usr/lib64/nagios/plugins/check_nrpe
    - /usr/local/nagios/libexec/check_nrpe

- name: Move check_nrpe plugin to plugins_directory
  copy:
    src: "{{ default_nrpe_directory }}/check_nrpe"
    dest: "{{ plugins_directory }}/check_nrpe"
    owner: nagios
    group: nagcmd
    mode: '2755'
    remote_src: yes