- name: Create Nagios config file from template
  template:    
    src: templates/nagios.cfg.j2
    dest: /usr/local/nagios/etc/nagios.cfg
    mode: "2775"
    owner: "nagios"
    group: "nagcmd"
  when: set_custom_paths


- name: Ensure Nagios custom directories exist
  file:
    path: "{{ item }}"
    state: directory
    mode: "2775"
    owner: "nagios"
    group: "nagcmd"
  loop:
    - "{{ nagios_custom_config.objects_dir }}"
    - "{{ nagios_custom_config.host_dir }}"
    - "{{ nagios_custom_config.clients_dir }}"

- name: Generate Nagios Server configuration for localhost
  template:
    src: templates/localhost.cfg.j2
    dest: "{{ nagios_custom_config.host_dir }}/localhost.cfg"
    mode: "2775"
    owner: "nagios"
    group: "nagcmd"


- name: Restart Nagios Server
  systemd:
    name: nagios
    state: restarted