- name: Ensure nrpe_commands is available
  debug:
    var: nrpe_commands
    
- name: Ensure clients directory exists
  file:
    path: "{{ clients_folder_path }}"
    state: directory
    owner: nagios
    group: nagcmd
    mode: '2755'

- name: Generate Nagios client config
  template:
    src: templates/nagios_client.cfg.j2
    dest: "{{ clients_folder_path }}/{{ item }}.cfg"
    owner: nagios
    group: nagcmd
    mode: '2755'
  loop: "{{ groups['clients'] }}"
 

- name: Set owner and group for Nagios client config
  file:
    path: "{{ clients_folder_path }}/{{ item }}.cfg"
    owner: nagios
    group: nagcmd
    mode: '2755'
  loop: "{{ groups['clients'] }}"
  notify: Restart Nagios Server