- name: Ensure nrpe_commands is available
  debug:
    var: nrpe_commands
    
- name: Ensure clients directory exists
  file:
    path: "{{ clients_folder_path }}"
    state: directory
    owner: nagios
    group: nagcmd
    mode: '2755'

- name: Generate Nagios client config
  template:
    src: templates/nagios_client.cfg.j2
    dest: "{{ clients_folder_path }}/{{ item }}.cfg"
    owner: nagios
    group: nagcmd
    mode: '2755'
  loop: "{{ groups['clients'] }}"
  vars:
    client_ip: "{{ hostvars[item]['ansible_host'] }}"
    client_hostname: "{{ hostvars[item]['ansible_hostname'] }}"
 

- name: Set owner and group for Nagios client config
  file:
    path: "{{ clients_folder_path }}/{{ item }}.cfg"
    owner: nagios
    group: nagcmd
    mode: '2755'
  loop: "{{ groups['clients'] }}"


- name: Kill all nagios processes
  command: pkill -9 nagios
  ignore_errors: yes

- name: Restart Nagios Server
  systemd:
    name: nagios
    state: restarted