set_custom_paths: true
nagios_hostname: "Nagios_Server"
nagios_server_alias: "Nagios_Server"
hostgroup_name: "linux-servers" #no spaces allowed
hostgroup_alias: "Linux Server"
nagios_host_address: "127.0.0.1"


nagios_custom_config:
  objects_dir: "/usr/local/nagios/etc/objects"
  host_dir: "/usr/local/nagios/etc/host"
  clients_dir: "/usr/local/nagios/etc/clients"

# Default monitors thresholds
nagios_monitors:
  check_local_load:
    enabled: true
    description: "Current Load"
    params: "5.0,4.0,3.0!10.0,6.0,4.0"

  check_local_users:
    enabled: true
    description: "Current Users"
    params: "20!50"

  check_http:
    enabled: true
    description: "HTTP"
    params: ""

  check_ping:
    enabled: true
    description: "PING"
    params: "100.0,20%!500.0,60%"
  
  
  check_local_disk:
    enabled: true
    description: "Root Partition"
    params: "20%!10%!/"
  
  check_ssh:
    enabled: true
    description: "SSH"
    params: ""

  check_local_procs:
    enabled: true
    description: "Total Processes"
    params: "250!400!RSZDT"

  check_local_swap:
    enabled: true  
    description: "Swap Usage"
    params: "20%!10%"
  


