- name: Install required dependencies for Nagios Core
  dnf:
    name:
      - gcc
      - glibc
      - glibc-common
      - make
      - gettext
      - automake
      - autoconf
      - wget
      - openssl-devel
      - net-snmp
      - net-snmp-utils
      - epel-release
      - perl-Net-SNMP
      - httpd
      - php
      - glibc-devel
      - gd
      - gd-devel
      - unzip
      - libmcrypt
      - libmcrypt-devel
      - libcurl-devel
      - libtool
      - pkg-config
    state: present
  tags: dependencies