- name: Set SELinux to permissive mode temporarily
  command: setenforce 0
  ignore_errors: true


- name: Install EPEL repository on Centos9
  dnf:
    name: epel-release
    state: present


- name: Update and upgrade system packages
  dnf:
    name: "*"
    state: latest
  tags: update