- name: Create Nagios user with home directory and shell
  user:
    name: nagios
    create_home: yes
    shell: /bin/bash


- name: Create Nagcmd group for external commands
  group:
    name: nagcmd
    state: present


- name: Add nagios user to nagcmd group
  user:
    name: nagios
    groups: nagcmd
    append: yes


- name: Add apache user to nagcmd group
  user:
    name: apache
    groups: nagcmd
    append: yes


- name: Download Nagios Core Source
  get_url:
    url: https://assets.nagios.com/downloads/nagioscore/releases/nagios-4.4.12.tar.gz
    dest: /tmp/nagios.tar.gz


- name: Extract Nagios Core source
  unarchive:
    src: /tmp/nagios.tar.gz
    dest: /tmp/
    remote_src: yes


- name: Compile and install Nagios Core
  shell: |
    cd /tmp/nagios-4.4.12
    ./configure --with-command-group=nagcmd
    make all
    make install
    make install-init
    make install-config
    make install-commandmode
    make install-webconf
  args:
    executable: /bin/bash


- name: Configure Nagios admin account
  shell: htpasswd -bc /usr/local/nagios/etc/htpasswd.users nagiosadmin password
  args:
    executable: /bin/bash
  no_log: true


- name: Configure SELinux to allow Apache
  command: setsebool -P httpd_can_network_connect 1


- name: Enable and start Apache
  systemd:
    name: httpd
    state: started
    enabled: true


- name: Enable and start Nagios
  systemd:
    name: nagios
    state: started
    enabled: true
